# Site settings
title: Mehmet Cem Yücel
description: 'En yalın haliyle Türkçe yazılım blogu.<br/> Java, Cloud, Mikroservisler, Spring Boot, NoSQL, Kafka, Dağıtık Sistemler ve Blockchain konuları hakkında karalamalarım'
keywords: 'Mehmet Cem Yücel, Türkçe, Yazılım, Bilgisayar, örnek, kod, Blog, Blogger, Nedir, Nasıl yapılır, Spring, Java, Mikroservis, Blockchain, Cloud, framework, servis, uygulama'
url: 'https://www.mehmetcemyucel.com'
baseurl: ''
google_analytics: 'UA-134372019-2'
disqus_shortname: 'mehmetcemyucel'
language: tr
revisit-after: 14 days
environment: production
author:
  name: 'Mehmet Cem Yücel'
  email: admin@mehmetcemyucel.com
  twitter_username: mehmetcemyucel
  facebook_username: m.cem.yucel
  github_username:  mehmetcemyucel
  linkedin_username:  mehmetcemyucel
  stackoverflow_username: mehmetcemyucel

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
